apiVersion: batch/v1
kind: CronJob
metadata:
  name: nlp-job-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nlp-job
            image: gcr.io/news-drop/nlp-bot:0.0.3
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-nlp
                  key: API_KEY
            resources:
              requests:
                memory: "100Mi"
                cpu: "50m"
              limits:
                memory: "200Mi"
                cpu: "100m"
          restartPolicy: OnFailure
