apiVersion: apps/v1
kind: Deployment
metadata:
  name: outstanding-bot-deployment-en-us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outstanding-bot-en-us
  template:
    metadata:
      labels:
        app: outstanding-bot-en-us
    spec:
      containers:
      - name: news-drop-container-1
        image: gcr.io/news-drop/outstanding:0.0.4
        resources:
          limits:
            cpu: "10m"
            memory: "50Mi"
          requests:
            cpu: "4m"
            memory: "20Mi"
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USER
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_NAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: language
            value: "en"
          - name: country
            value: "US"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: outstanding-bot-deployment-es-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outstanding-bot-es-es
  template:
    metadata:
      labels:
        app: outstanding-bot-es-es
    spec:
      containers:
      - name: news-drop-container-1
        image: gcr.io/news-drop/outstanding:0.0.4
        resources:
          limits:
            cpu: "10m"
            memory: "50Mi"
          requests:
            cpu: "4m"
            memory: "20Mi"
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USER
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_NAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: language
            value: "es"
          - name: country
            value: "ES"
---
