apiVersion: apps/v1
kind: Deployment
metadata:
  name: outstanding-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outstanding-bot
  template:
    metadata:
      labels:
        app: outstanding-bot
    spec:
      containers:
      - name: news-drop-container-1
        image: gcr.io/news-drop/outstanding:0.0.2
        resources:
          limits:
            cpu: "10m"
            memory: "50Mi"
          requests:
            cpu: "4m"
            memory: "20Mi"
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USER
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_NAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
