apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-news-drop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-news-drop
  template:
    metadata:
      labels:
        app: django-news-drop
    spec:
      containers:
      - name: django-container-news-drop
        image: gcr.io/news-drop/django-container-news-drop:0.4.5
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: SECRET_KEY
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: django-db-credentials 
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: django-db-credentials 
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: django-db-credentials 
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-db-credentials 
              key: DB_PASSWORD
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/news-drop-796857b8eb91.json
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "300Mi"
            cpu: "100m"
      volumes:
      - name: secret-volume
        secret:
          secretName: bucket-secret-key
          items:
          - key: news-drop-796857b8eb91.json
            path: news-drop-796857b8eb91.json


---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - app.newsdropped.com
---


apiVersion: v1
kind: Service
metadata:
  name: django-clusterip-service
spec:
  selector:
    app: django-news-drop
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-to-https
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: newsdropped-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "http-to-https"
spec:
  rules:
    - host: app.newsdropped.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: django-clusterip-service
                port:
                  number: 80

---

