apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api-namescape-news-drop
  name: api-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
