apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-role-binding
  namespace: bots
subjects:
- kind: ServiceAccount
  name: api-serviceaccount-kubernetes
  namespace: api
roleRef:
  kind: Role
  name: api-role
  apiGroup: rbac.authorization.k8s.io
