# Generated by Django 5.0.6 on 2024-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drops',
            options={'verbose_name_plural': 'Drops'},
        ),
        migrations.AlterField(
            model_name='drops',
            name='bot_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
