# Generated by Django 5.0.6 on 2024-07-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_alter_drops_options_alter_drops_bot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drops',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drops',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
