# Generated by Django 5.0.6 on 2024-07-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0003_drops_country_drops_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drops',
            name='language',
        ),
    ]
