apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-news-drop
  labels:
    app: api-news-drop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-news-drop
  template:
    metadata:
      labels:
        app: api-news-drop
    spec:
      serviceAccountName: api-serviceaccount-kubernetes
      containers:
        - name: api-container-news-drop
          image: gcr.io/news-drop/news-drop-api:0.3.5
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "30m"
              memory: "80Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-news-drop-service
spec:
  selector:
    app: api-news-drop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
