# apiVersion: v1
# kind: Pod
# metadata:
#   name: api-news-drop
# spec:
#   serviceAccountName: api-serviceaccount-kubernetes
#   containers:
#   - name: api-container-news-drop
#     image: gcr.io/news-drop/news-drop-api:0.2.1
#     # command: ["sleep","infinity"]

apiVersion: v1
kind: Pod
metadata:
  name: api-news-drop
  labels:
    app: api-news-drop
spec:
  serviceAccountName: api-serviceaccount-kubernetes
  containers:
  - name: api-container-news-drop
    image: gcr.io/news-drop/news-drop-api:0.2.1
    ports:
      - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-news-drop-service
spec:
  selector:
    app: api-news-drop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
